version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./data/reports:/app/data/reports
      - ./data/rules:/app/data/rules
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Kolkata
      - DATABASE_URL=postgresql://reportuser:reportpass@db:5432/reportdb

      - POSTGRES_SERVER=db
      - POSTGRES_USER=reportuser
      - POSTGRES_PASSWORD=reportpass
      - POSTGRES_DB=reportdb
      - POSTGRES_PORT=5432

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - UPLOAD_FOLDER=/app/data/uploads
      - REPORT_FOLDER=/app/data/reports
      - RULES_FOLDER=/app/data/rules

      - CSV_CHUNK_SIZE=50000
      - MAX_WORKERS=8
      - PYTHONHASHSEED=0
      - OMP_NUM_THREADS=8
      - OPENBLAS_NUM_THREADS=4
      - MKL_NUM_THREADS=4
      - NUMEXPR_NUM_THREADS=4
      - DASK_DISTRIBUTED__WORKER__MEMORY__SPILL=0.85
      - DASK_DISTRIBUTED__WORKER__MEMORY__TARGET=0.75
      - API_KEY=dev_api_key

    depends_on:
      - db
      - redis
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=reportuser
      - POSTGRES_PASSWORD=reportpass
      - POSTGRES_DB=reportdb
    ports:
      - "5433:5432"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reportuser -d reportdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: on-failure

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: on-failure

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data: